Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,3 +24,41 @@ jobs:
 
       - name: Docker Push
         run: docker push ${{ secrets.DOCKER_USERNAME }}/ninesoftech
+        
+      - name: Set up SSH key and whitelist EC2 IP address 🐻‍❄️
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      # Step 3: SSH into EC2 and create the target directory
+      - name: SSH into EC2 and create target directory 🚀
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
+            mkdir -p /home/ubuntu/taoshi-be/
+          "
+
+      # Step 4: Copy files to remote server
+      - name: Copy files to remote server 🚙
+        run: |
+          scp -r * ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/taoshi-be/
+
+      # Step 5: SSH into EC2 instance, pull latestS code, and deploy Docker container
+      - name: SSH into EC2 and deploy Docker container 🚀
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
+            cd /home/ubuntu/taoshi-be/
+            sudo apt update -y || true
+            sudo git pull origin master
+            sudo apt install docker.io* -y || true
+            sudo docker stop my-nodjs-app || true
+            sudo docker rm my-nodejs-app || true
+            sudo docker run -d --name my-nodejs-app -p 5000:5000 saivanapalli29/ninesoftech
+          "
+
+      # Step 6: Clean up SSH key
+      - name: Clean up SSH key 🚀
+        if: always()
+        run: rm -f ~/.ssh/id_rsa
+     
